title: Rodrigo Chueri
logo: /assets/img/avatar.jpg
description: Aluno de engenharia mecânica pela UFRJ, participou da equipe de competição UFRJ Nautilis no departamento de hidromecânica. Principais interesses envolvem vasos de pressão, combustão e modelagem computacional. Experiência como programador em C#, Python e C++.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
